### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by ale2317** [cybertec-postgresql/walbouncer#1]
Get the following error:

gcc -O2 -Wall -Werror -g -I/usr/local/pg951/include -Iinclude -c wbcrc32c.c -o wbcrc32c.o
wbcrc32c.c:22:22: fatal error: wbcrc32c.h: Datei oder Verzeichnis nicht gefunden
 #include "wbcrc32c.h"
                      ^
compilation terminated.
make: **\* [wbcrc32c.o] Fehler 1

Regards

Alex

**Comment by kmoppel** [comment]
Uups, a file went missing somewhere indeed :) Is there now  https://github.com/cybertec-postgresql/walbouncer/commit/05bc904c3255b4050ab7d77b8a7d1a5996042090
