### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by ale2317** [cybertec-postgresql/walbouncer#2]
gcc -O2 -Wall -Werror -g -I/usr/local/pg951/include -Iinclude -c wbcrc32c.c -o wbcrc32c.o
gcc -O2 -Wall -Werror -g -I/usr/local/pg951/include -Iinclude -c wbmasterconn.c -o wbmasterconn.o
gcc -O2 -Wall -Werror -g -I/usr/local/pg951/include -Iinclude -c wbfilter.c -o wbfilter.o
wbfilter.c: In function ‘WriteNoopRecord’:
wbfilter.c:438:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = REC_HEADER_LEN + SizeOfXLogRecordDataHeaderLong; i < fl->bufferLen; i++)
     ^
wbfilter.c:438:5: note: use option -std=c99 or -std=gnu99 to compile your code
make: **\* [wbfilter.o] Fehler 1

**Comment by kmoppel** [comment]
Hi! This could be worked around with the suggested compiler directive. I've now added the -std=gnu99 flag also to Makefile as it should be harmless enough.
https://github.com/cybertec-postgresql/walbouncer/commit/c7eb08b7ee0a7e2474bb8efce015dfa76db3778a

**Comment by ale2317** [comment]
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c main.c -o main.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbsocket.c -o wbsocket.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbutils.c -o wbutils.o
flex -o parser/repl_scanner.c parser/repl_scanner.l
bison -o parser/repl_gram.c parser/repl_gram.y
parser/repl_gram.y:45.1-13: Warnung: veraltete Direktive, benutzen Sie „%name-prefix“ [-Wdeprecated]
 %name-prefix="replication_yy"
 ^^^^^^^^^^^^^
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c parser/repl_gram.c -o parser/repl_gram.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c parser/scansup.c -o parser/scansup.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c parser/stringinfo.c -o parser/stringinfo.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c parser/gram_support.c -o parser/gram_support.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbcrc32c.c -o wbcrc32c.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbmasterconn.c -o wbmasterconn.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbfilter.c -o wbfilter.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbclientconn.c -o wbclientconn.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbsignals.c -o wbsignals.o
gcc -O2 -Wall -Werror -g -std=gnu99 -I/usr/local/pg951/include -Iinclude -c wbconfig.c -o wbconfig.o
gcc -O2 -Wall -Werror -g -std=gnu99 -o walbouncer main.o wbsocket.o wbutils.o parser/repl_gram.o parser/scansup.o parser/stringinfo.o parser/gram_support.o wbcrc32c.o wbmasterconn.o wbfilter.o wbclientconn.o wbsignals.o wbconfig.o -I -L/usr/local/pg951/lib -lpq -lyaml
/usr/bin/ld: cannot find -lpq
collect2: error: ld returned 1 exit status
make: **\* [walbouncer] Fehler 1

**Comment by kmoppel** [comment]
Seems libpq package is missing on the system. On Ubuntu for example one can install it with "sudo apt-get install libpq-dev"
