### ISSUE TITLE
Missing or extra transaction with multiple slaves

### ISSUE THREAD

**Issue by ajgillis** [cybertec-postgresql/walbouncer#6]
When there are multiple slaves and master goes down, slave-1 and slave-2 may be at slightly different points in replication (suppose network latency).  Suppose slave-2 has one additional transaction that did not get replicated to slave-1 when master died.  When slave-1 is promoted to master and slave-2 is proxied to new master, replication will fail on slave-2 since it has that extra transaction.  Seems that slave-2 must first be restored from base backup of new master before replication can start.

The README says, "For clusters with more than two slaves you can change a slave servers effective primary_conninfo without restarting PostgreSQL by proxying it through walbouncer and changing walbouncer config when master server location changes."

Maybe just a doc change, or maybe I am misunderstanding something, but it seems like postgres would need to restart on all other slaves due to syncing them with new master.

**Comment by kovmir** [comment]
Dead, re-open if needed.
