### ISSUE TITLE
PDF Link is broken

### ISSUE THREAD

**Issue by doronyaary** [cybertec-postgresql/walbouncer#8]
Hello,

The link to the concepts PDF is broken. It would be much appreciated if you can include a new link.

Thanks!

**Comment by war59312** [comment]
https://www.cybertec-postgresql.com/wp-content/uploads/2017/10/walbouncer.pdf

**Comment by kovmir** [comment]
Dead.

**Comment by war59312** [comment]
Was just moved.

It's now at https://www.cybertec-postgresql.com/wp-content/uploads/2024/02/walbouncer.pdf

@kovmir
